language: cpp

compiler:
  - gcc

script:
  - "sudo add-apt-repository ppa:tboox/xmake && sudo apt-get update && sudo apt-get install -y xmake"
  - "xmake && xmake run"

notifications:
  email: lygjcsrq@163.com