language: cpp

compiler:
  - gcc

install:
  - "sudo apt install -y libtool automake"
  - "wget https://github.com/xmake-io/xmake/releases/download/v2.2.8/xmake-v2.2.8.amd64.deb && sudo dpkg -i xmake-v2.2.8.amd64.deb"

script:
  - "xmake -y -v && xmake run"

notifications:
  email: lygjcsrq@163.com