version: 2.1
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - run: bash <(wget https://raw.githubusercontent.com/tboox/xmake/master/scripts/get.sh -O -)
      - checkout # check out the code in the project directory
      - run: xmake && xmake run